; platformio.ini
[env:esp32-s3]
platform = espressif32
board = esp32-s3-devkitc-1   ; generic S3, we override partition below
framework = arduino
board_build.arduino.memory_type = qio_opi
board_build.partitions = huge_app.csv
monitor_speed = 115200
lib_deps = 
    lovyan03/LovyanGFX@^1.1.12
    lvgl/lvgl@^8.3.11
    h2zero/NimBLE-Arduino@^1.4.0
    sd_MMC   ; or sdfat depending on your SD interface
build_flags = 
    -DLV_CONF_INCLUDE_SIMPLE
    -Iinclude
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCONFIG_NIMBLE_CPP_LOG_LEVEL=0